- hosts: myweb
  vars:
    - "newroot": "/var/www/newroot"
  tasks:
  - name: "Installing the package"
    package:
      name: "httpd"
      state: present
  - name: "Creating the directory"
    file:
      path: "{{ newroot }}"
      state: directory
  - name: "Adding Configuration File"
    template:
      src: "ab.conf"
      dest: "/etc/httpd/conf.d/ab.conf"
    notify:
    - "Starting the service"
  handlers:
    - name: "Starting the service"
      service:
        name: "httpd"
        state: restarted
        enabled: yes
